### ISSUE TITLE
3.3/5V outputs

### ISSUE THREAD

**Issue by Nosovsergeyal** [kajusK/CNCHat#2]
I can’t figure out where the 3.3/5V outputs are for the stepper motor drivers

**Comment by kajusK** [comment]
There's no switch for the steppers output signals, the high level output voltage is fixed to 3.3 V.

 This should work on both the 3.3 and 5 V drivers as the 5V TTL logic specifies a minimum high level input voltage as 2 V, actually the minimum output level for 5 V is 2.7 V, so the 3.3 V output is perfectly within 5 V TTL specs.

I've pushed a PDF schematic to the repo so if you don't have the KiCad installed, you can take a look in schematic anyway to see how it's routed.

There's only one selectable voltage switch - the JP1, it's used to select a power voltage for endstop inputs.

**Comment by Nosovsergeyal** [comment]
@kajusK Is there any way I can contact you?

**Comment by kajusK** [comment]
I guess you've just contacted me :).
